### ISSUE TITLE
Cannot connect to servers via ssl

### ISSUE THREAD

**Issue by daniel-montalvo** [instantbird/instantbird-build#1]
It appears to me that InstantBird does not connect via SSL.

Steps to reproduce:
* Show the accounts menu and add the account with username and password, server address, port 6697, SSL check and nickname.
* Try to connect the account.

Expected result: The account will connect and you will be able to select the channels to join.

Obtained result: The button "Connect" changes to "Disconnect" but then changes to "Connect" again, and it is not possible to get the list of available channels since connections seems to be interrupted.

Connection can be made to this very server for public channels (without SSL) but not for private channels.

**Comment by clokep** [comment]
This is not a bug tracker for Instantbird. Instantbird is not being developed anymore.
